export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const SET_CATEGORY = "SET_CATEGORY";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_POSTS = "SET_POSTS";
export const FETCH_REQUEST = "FETCH_REQUEST";
